---
Name: stevenpaw-silverstripe-cms-backend-theme
---
SilverStripe\Admin\LeftAndMain:
  extensions:
    - StevenPaw\SilverStripeCMSBackendTheme\Extensions\LeftAndMainExtension
    - StevenPaw\SilverStripeCMSBackendTheme\Extensions\GroupedCmsMenu

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - StevenPaw\SilverStripeCMSBackendTheme\Extensions\SiteConfigExtension
